### ISSUE TITLE
RTE does not work with LitElement (ES Modules?)

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-rich-text-editor#111] opened 2019-02-26 06:11 UTC
Code:
```javascript
import {
  html, LitElement
} from 'lit-element';
import '@vaadin/vaadin-rich-text-editor';

class ContentView extends LitElement {

  render() {
    return html `<vaadin-rich-text-editor></vaadin-rich-text-editor>`;
  }
}

customElements.define('content-view', ContentView);
```

Running this code gives the following error in the console.
```
Uncaught TypeError: Cannot read property 'imports' of undefined
    at HTMLElement._prepareToolbar (vaadin-rich-text-editor.js:446)
    at HTMLElement.ready (vaadin-rich-text-editor.js:388)
    at HTMLElement._enableProperties (properties-changed.js:331)
    at HTMLElement.connectedCallback (properties-mixin.js:208)
    at HTMLElement.connectedCallback (element-mixin.js:600)
    at NodePart._insert (parts.js:192)
    at NodePart._commitNode (parts.js:199)
    at NodePart._commitTemplateResult (parts.js:231)
    at NodePart.commit (parts.js:172)
    at render (render.js:44)
```

The component is visible, but you can't for example click on the content to type anything in.

The resulting row is vaadin-rich-text-editor.js:446
```
  _prepareToolbar() {
    const clean = Quill.imports['modules/toolbar'].DEFAULTS.handlers.clean;
```
Seems like the global `Quill` object is not initialized.

**Comment by web-padawan** [comment] 2019-02-26 06:27
Duplicate of #101
See https://github.com/vaadin/vaadin-rich-text-editor/blob/master/README.md#bundling-with-webpack

**Comment by Peppe** [comment] 2019-02-26 07:31
Damn. I forgot that part again. :( Not nice that it doesn't work out of the box.

**Closed** 2019-06-10 07:50 UTC
