### ISSUE TITLE
Allow customization of the toolbar

### ISSUE THREAD

**Issue by jm2rodriguez** [vaadin/vaadin-rich-text-editor#126] opened 2019-10-30 10:31 UTC
Allow to enable/disable each button in the toolbar.

To limit the functionalities to users, it may be interesting to create an empty toolbar. The functionalities are then activated by enabling the corresponding buttons in the toolbar.

**Comment by heruan** [comment] 2019-10-30 11:14
Related to #113 and #118

**Comment by web-padawan** [comment] 2020-02-20 13:38
Closing as duplicate of #118.

**Closed by web-padawan** 2020-02-20 13:38 UTC
